# Generated by Django 4.1.13 on 2024-01-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.CharField(max_length=255, null=True)),
                ('subdomain', models.CharField(max_length=255)),
                ('amocrm_id', models.CharField(max_length=255)),
                ('secret_key', models.TextField()),
                ('access_code', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AMOCRM token',
                'verbose_name_plural': 'AMOCRM tokens',
            },
        ),
    ]
